import { ipToBigInt, bigIntToIp, parseCidr, bigIntToIpv6 } from './ip';

interface Interval {
    start: bigint;
    end: bigint;
    version: 4 | 6;
}

/**
 * Merges overlapping or adjacent intervals (same version only).
 */
export function mergeIntervals(intervals: Interval[]): Interval[] {
    if (intervals.length === 0) return [];
    
    // Check version consistency
    const version = intervals[0].version;
    if (intervals.some(i => i.version !== version)) throw new Error('Mixed versions in mergeIntervals');
    
    const sorted = [...intervals].sort((a, b) => (a.start < b.start ? -1 : a.start > b.start ? 1 : 0));
    
    const result: Interval[] = [];
    let current = sorted[0];
    
    for (let i = 1; i < sorted.length; i++) {
        const next = sorted[i];
        if (current.end + 1n >= next.start) {
            current.end = current.end > next.end ? current.end : next.end;
        } else {
            result.push(current);
            current = next;
        }
    }
    result.push(current);
    return result;
}

/**
 * Subtracts excludes from base (same version).
 */
export function subtractIntervals(base: Interval, excludes: Interval[]): Interval[] {
    if (excludes.some(e => e.version !== base.version)) throw new Error('Version mismatch');
    
    const sortedExcludes = mergeIntervals(excludes);
    const result: Interval[] = [];
    
    let currentStart = base.start;
    
    for (const exclude of sortedExcludes) {
        if (exclude.start > base.end) break;
        if (exclude.end < currentStart) continue;
        
        const overlapStart = exclude.start > currentStart ? exclude.start : currentStart;
        const overlapEnd = exclude.end < base.end ? exclude.end : base.end;
        
        if (overlapStart > currentStart) {
            result.push({ start: currentStart, end: overlapStart - 1n, version: base.version });
        }
        currentStart = overlapEnd + 1n;
        if (currentStart > base.end) break;
    }
    
    if (currentStart <= base.end) {
        result.push({ start: currentStart, end: base.end, version: base.version });
    }
    
    return result;
}

/**
 * Converts range to minimal CIDRs.
 */
export function rangeToCidrs(start: bigint, end: bigint, version: 4 | 6): string[] {
    const cidrs: string[] = [];
    let current = start;
    const maxBits = version === 4 ? 32n : 128n;
    
    while (current <= end) {
        // Find largest power of 2 (alignment)
        let bits = 0n;
        // Optimization for BigInt loop: find LSb?
        // Or just limit loop. 32 or 128 iterations is fine.
        while (bits < maxBits && current % (2n << bits) === 0n) {
            bits++;
        }
        
        while (bits >= 0n) {
            const width = 1n << bits;
            if (current + width - 1n <= end) {
                const prefix = maxBits - bits;
                const ipStr = version === 4 ? bigIntToIp(current) : bigIntToIpv6(current);
                cidrs.push(`${ipStr}/${prefix}`);
                current += width;
                break;
            }
            bits--;
        }
    }
    return cidrs;
}

/**
 * Main function.
 * fullRanges defaults to dual stack "everything".
 */
export function calculateAllowedIPs(
    excludedCidrs: string[], 
    fullRanges: string[] = ['0.0.0.0/0', '::/0']
): string[] {
    
    const excludesV4: Interval[] = [];
    const excludesV6: Interval[] = [];
    
    // Parse Excludes
    for (const cidr of excludedCidrs) {
        if (!cidr.trim()) continue;
        try {
            const parsed = parseCidr(cidr.trim());
            if (parsed.version === 4) excludesV4.push({ start: parsed.start, end: parsed.end, version: 4 });
            else excludesV6.push({ start: parsed.start, end: parsed.end, version: 6 });
        } catch (e) {
            console.warn(`Skipping invalid CIDR: ${cidr}`, e);
        }
    }
    
    const resultCidrs: string[] = [];
    
    // Process Full Ranges (can be multiple)
    for (const fullCidr of fullRanges) {
        try {
            const parsed = parseCidr(fullCidr);
            const base: Interval = { start: parsed.start, end: parsed.end, version: parsed.version === 4 ? 4 : 6 };
            const excludes = parsed.version === 4 ? excludesV4 : excludesV6;
            
            const allowed = subtractIntervals(base, excludes);
            for (const interval of allowed) {
                resultCidrs.push(...rangeToCidrs(interval.start, interval.end, interval.version));
            }
        } catch(e) {
            console.error(e);
        }
    }
    
    // Sort? Not strictly necessary but nice.
    // Default order is generated by interval. Mixing v4 and v6 is fine.
    
    return resultCidrs;
}
